import type { Product, CategoryInfo, SubcategoryInfo } from './types';

export const COMPANY = {
  name: 'Borboletas',
  tagline: 'Detalles hechos con amor',
  slogan: 'Regalos artesanales hechos a mano con calidad y servicio. Cada pieza es elaborada con dedicacion para hacer de tu momento algo unico e inolvidable.',
  instagram: 'https://www.instagram.com/borboletas_bog/',
  instagramHandle: '@borboletas_bog',
  whatsapp: '+57 333 266 1702',
  whatsappMessage: 'Hola! Me interesa un producto de Borboletas 🦋',
  city: 'Bogota, Colombia',
  logo: 'https://i.postimg.cc/8cs0rvJm/logo-borboletas.png',
};

export const CATEGORIES: CategoryInfo[] = [
  {
    key: 'navidad',
    label: 'Epoca de Navidad',
    emoji: '🎄',
    description: 'Decoracion navidena artesanal para llenar tu hogar de magia y espiritu navideno',
    gradient: 'from-red-700 via-red-600 to-green-700',
    accentColor: 'text-red-600',
  },
  {
    key: 'halloween',
    label: 'Epoca de Halloween',
    emoji: '🎃',
    description: 'Figuras terrorificamente adorables para la noche mas divertida del ano',
    gradient: 'from-orange-600 via-orange-500 to-purple-800',
    accentColor: 'text-orange-600',
  },
  {
    key: 'desayunos_sorpresa',
    label: 'Decoracion Desayunos Sorpresa',
    emoji: '🎁',
    description: 'Detalles artesanales para sorprender con un desayuno inolvidable',
    gradient: 'from-pink-500 via-rose-400 to-amber-400',
    accentColor: 'text-pink-500',
  },
  {
    key: 'lapices_cuadernos',
    label: 'Lapices y Cuadernos',
    emoji: '✏️',
    description: 'Utiles escolares decorados a mano con personajes unicos y coloridos',
    gradient: 'from-blue-500 via-cyan-400 to-teal-500',
    accentColor: 'text-blue-600',
  },
  {
    key: 'tejidos',
    label: 'Tejidos',
    emoji: '🧶',
    description: 'Piezas tejidas a mano con lana de alta calidad, cada puntada hecha con amor',
    gradient: 'from-rose-400 via-fuchsia-400 to-violet-500',
    accentColor: 'text-fuchsia-600',
  },
];

export const NAVIDAD_SUBCATEGORIES: SubcategoryInfo[] = [
  { key: 'noel', label: 'Papa y Mama Noel', emoji: '🎅' },
  { key: 'renos', label: 'Renos y Renas', emoji: '🦌' },
  { key: 'osos_polares', label: 'Osos Polares', emoji: '🐻‍❄️' },
  { key: 'munecos_nieve', label: 'Munecos de Nieve', emoji: '⛄' },
  { key: 'pie_arbol_cojines', label: 'Pie de Arbol y Cojines', emoji: '🎁' },
];

// ============================
// PRODUCTOS CON IMAGENES REALES
// ============================

const IMG = 'https://i.postimg.cc';

export const SAMPLE_PRODUCTS: Product[] = [
  // ========== NAVIDAD ==========
  {
    id: 'nav-01',
    subcategory: 'pie_arbol_cojines',
    name: 'Bota Navidena Decorativa',
    description: 'Hermosa bota navidena artesanal elaborada en foamy. Ideal para colgar en la chimenea o decorar tu hogar en esta epoca especial.',
    price: 0,
    discountPercent: 0,
    category: 'navidad',
    images: [`${IMG}/fLM4kkfk/bota-navidad.png`],
    customizable: true,
    featured: true,
    active: true,
    createdAt: '2026-03-01',
  },
  {
    id: 'nav-02',
    subcategory: 'pie_arbol_cojines',
    name: 'Cojines Navidenos - Coleccion Completa',
    description: 'Set de cojines navidenos decorativos elaborados a mano. Perfectos para ambientar tu sala con el espiritu de la Navidad.',
    price: 0,
    discountPercent: 20,
    category: 'navidad',
    images: [`${IMG}/pTPNyyJd/cojines-navidad-completo.png`],
    customizable: true,
    featured: true,
    active: true,
    createdAt: '2026-03-02',
  },
  {
    id: 'nav-03',
    subcategory: 'noel',
    name: 'Papa Noel Carita',
    description: 'Tierna carita de Papa Noel elaborada en foamy de alta calidad. Detalle decorativo con acabados pintados a mano.',
    price: 0,
    discountPercent: 0,
    category: 'navidad',
    images: [`${IMG}/gJsChdMm/face-papa-noe.png`],
    customizable: false,
    featured: false,
    active: true,
    createdAt: '2026-03-03',
  },
  {
    id: 'nav-04',
    subcategory: 'noel',
    name: 'Mama Noel Artesanal',
    description: 'Encantadora figura de Mama Noel hecha a mano con foamy. Cada detalle es cuidadosamente elaborado para dar vida a esta pieza unica.',
    price: 0,
    discountPercent: 15,
    category: 'navidad',
    images: [`${IMG}/yxr2fj4t/mama-noe-3.png`],
    customizable: true,
    featured: true,
    active: true,
    createdAt: '2026-03-04',
  },
  {
    id: 'nav-05',
    subcategory: 'noel',
    name: 'Mama Noel Azul',
    description: 'Version moderna de Mama Noel en tonos azules. Pieza artesanal con detalles delicados y acabado premium.',
    price: 0,
    discountPercent: 0,
    category: 'navidad',
    images: [`${IMG}/1tvdtBt4/mama-noe-azul.png`],
    customizable: true,
    featured: false,
    active: true,
    createdAt: '2026-03-04',
  },
  {
    id: 'nav-06',
    subcategory: 'noel',
    name: 'Mama Noel Azul Elegante',
    description: 'Elegante figura de Mama Noel en tonalidad azul cielo. Acabado fino con detalles pintados a mano.',
    price: 0,
    discountPercent: 0,
    category: 'navidad',
    images: [`${IMG}/N07ShBvm/Mama-noel-azul-2.png`],
    customizable: true,
    featured: false,
    active: true,
    createdAt: '2026-03-04',
  },
  {
    id: 'nav-07',
    subcategory: 'munecos_nieve',
    name: 'Muneca de Nieve',
    description: 'Adorable muneca de nieve artesanal con bufanda y accesorios. Toque magico para tu decoracion navidena.',
    price: 0,
    discountPercent: 30,
    category: 'navidad',
    images: [`${IMG}/0jrBJSMN/muneca-de-nieve.png`],
    customizable: false,
    featured: true,
    active: true,
    createdAt: '2026-03-05',
  },
  {
    id: 'nav-08',
    subcategory: 'munecos_nieve',
    name: 'Muneca de Nieve Elegante',
    description: 'Figura de nieve con detalles elaborados en foamy. Pieza unica con acabados de primera calidad.',
    price: 0,
    discountPercent: 0,
    category: 'navidad',
    images: [`${IMG}/4dW0dPdx/muneca-nieve-2.png`],
    customizable: false,
    featured: false,
    active: true,
    createdAt: '2026-03-05',
  },
  {
    id: 'nav-09',
    subcategory: 'osos_polares',
    name: 'Oso Polar Navideno',
    description: 'Tierno oso polar artesanal con gorro navideno. Pieza decorativa perfecta para la temporada de fiestas.',
    price: 0,
    discountPercent: 0,
    category: 'navidad',
    images: [`${IMG}/hP6HT20d/oso-polar.png`],
    customizable: false,
    featured: false,
    active: true,
    createdAt: '2026-03-06',
  },
  {
    id: 'nav-10',
    subcategory: 'osos_polares',
    name: 'Oso Polar con Bufanda',
    description: 'Oso polar artesanal con bufanda tejida. Cada pieza es elaborada con amor y dedicacion.',
    price: 0,
    discountPercent: 25,
    category: 'navidad',
    images: [`${IMG}/g2h1D3ML/oso-polar-2.png`],
    customizable: false,
    featured: false,
    active: true,
    createdAt: '2026-03-06',
  },
  {
    id: 'nav-11',
    subcategory: 'osos_polares',
    name: 'Oso Polar Sentado',
    description: 'Adorable oso polar en posicion sentada. Decoracion navidena artesanal con acabados delicados.',
    price: 0,
    discountPercent: 0,
    category: 'navidad',
    images: [`${IMG}/rmjB4cfJ/oso-polar-5.png`],
    customizable: false,
    featured: false,
    active: true,
    createdAt: '2026-03-06',
  },
  {
    id: 'nav-12',
    subcategory: 'noel',
    name: 'Papa Noel Cafe',
    description: 'Papa Noel artesanal en tonos cafe y tierra. Pieza rustica con encanto navideno especial.',
    price: 0,
    discountPercent: 0,
    category: 'navidad',
    images: [`${IMG}/FRpMSmPQ/papa-noe-cafe-(1).png`],
    customizable: true,
    featured: false,
    active: true,
    createdAt: '2026-03-07',
  },
  {
    id: 'nav-13',
    subcategory: 'noel',
    name: 'Papa Noel Gris',
    description: 'Elegante Papa Noel en tonalidades grises. Estilo moderno y sofisticado para decoracion navidena.',
    price: 0,
    discountPercent: 0,
    category: 'navidad',
    images: [`${IMG}/RFdkt9PB/papa-noe-gris.png`],
    customizable: true,
    featured: false,
    active: true,
    createdAt: '2026-03-07',
  },
  {
    id: 'nav-14',
    subcategory: 'noel',
    name: 'Papa Noel Miron',
    description: 'Divertido Papa Noel con expresion curiosa. Figura artesanal en foamy que sacara sonrisas en tu hogar.',
    price: 0,
    discountPercent: 40,
    category: 'navidad',
    images: [`${IMG}/ZRHGNZwg/papa-noe-miron.png`],
    customizable: false,
    featured: true,
    active: true,
    createdAt: '2026-03-08',
  },
  {
    id: 'nav-15',
    subcategory: 'noel',
    name: 'Papa Noel Miron Grande',
    description: 'Version grande del Papa Noel miron. Ideal como centro de mesa o pieza decorativa principal.',
    price: 0,
    discountPercent: 0,
    category: 'navidad',
    images: [`${IMG}/vBhJnM0q/papa-noe-miron-2.png`],
    customizable: false,
    featured: false,
    active: true,
    createdAt: '2026-03-08',
  },
  {
    id: 'nav-16',
    subcategory: 'noel',
    name: 'Papa Noel Miron Deluxe',
    description: 'Papa Noel miron edicion especial con detalles adicionales. Pieza premium de coleccion.',
    price: 0,
    discountPercent: 0,
    category: 'navidad',
    images: [`${IMG}/26GsWm0H/papa-noe-miron-3.png`],
    customizable: false,
    featured: false,
    active: true,
    createdAt: '2026-03-08',
  },
  {
    id: 'nav-17',
    subcategory: 'noel',
    name: 'Papa Noel en Pano',
    description: 'Papa Noel elaborado en tela de pano con acabados artesanales. Suave al tacto y con detalles encantadores.',
    price: 0,
    discountPercent: 0,
    category: 'navidad',
    images: [`${IMG}/j5cpfKMm/papa-noe-pano.png`],
    customizable: true,
    featured: false,
    active: true,
    createdAt: '2026-03-09',
  },
  {
    id: 'nav-18',
    subcategory: 'noel',
    name: 'Papa Noel Verde',
    description: 'Papa Noel artesanal con traje verde. Un giro creativo y original al clasico personaje navideno.',
    price: 0,
    discountPercent: 0,
    category: 'navidad',
    images: [`${IMG}/T1h4WbLr/papa-noe-verde.png`],
    customizable: true,
    featured: false,
    active: true,
    createdAt: '2026-03-09',
  },
  {
    id: 'nav-19',
    subcategory: 'noel',
    name: 'Papa Noel Verde Elegante',
    description: 'Version premium del Papa Noel verde con acabados finos y detalles decorativos extra.',
    price: 0,
    discountPercent: 0,
    category: 'navidad',
    images: [`${IMG}/Vv5Vbtrd/papa-noe-verde-2.png`],
    customizable: true,
    featured: false,
    active: true,
    createdAt: '2026-03-09',
  },
  {
    id: 'nav-20',
    subcategory: 'noel',
    name: 'Papa Noel Azul',
    description: 'Papa Noel en tonos azules, estilo moderno y diferente. Pieza exclusiva hecha a mano.',
    price: 0,
    discountPercent: 35,
    category: 'navidad',
    images: [`${IMG}/BvGkwtk3/papa-noel-azul-2.png`],
    customizable: true,
    featured: false,
    active: true,
    createdAt: '2026-03-09',
  },
  {
    id: 'nav-21',
    subcategory: 'noel',
    name: 'Pareja de Papas Noel',
    description: 'Encantadora pareja de Papa y Mama Noel juntos. Set decorativo perfecto para la temporada.',
    price: 0,
    discountPercent: 20,
    category: 'navidad',
    images: [`${IMG}/XJLR53sP/papas-noe-pareja-2.png`],
    customizable: true,
    featured: true,
    active: true,
    createdAt: '2026-03-10',
  },
  {
    id: 'nav-22',
    subcategory: 'renos',
    name: 'Pareja de Renos Enamorados',
    description: 'Tierna pareja de renos navidenos. Pieza artesanal ideal para regalar en epoca navidena.',
    price: 0,
    discountPercent: 0,
    category: 'navidad',
    images: [`${IMG}/pTCwjxsC/pareja-renos-5.png`],
    customizable: true,
    featured: false,
    active: true,
    createdAt: '2026-03-10',
  },
  {
    id: 'nav-23',
    subcategory: 'pie_arbol_cojines',
    name: 'Pie de Arbol Navideno',
    description: 'Hermoso pie de arbol artesanal para decorar la base de tu arbol de Navidad con estilo y originalidad.',
    price: 0,
    discountPercent: 50,
    category: 'navidad',
    images: [`${IMG}/yxWbSRgh/Pie-de-arbol-2.png`],
    customizable: true,
    featured: true,
    active: true,
    createdAt: '2026-03-11',
  },
  {
    id: 'nav-24',
    subcategory: 'renos',
    name: 'Rena Navidena',
    description: 'Linda rena artesanal con detalles florales y lazos. Elaborada con foamy de primera calidad.',
    price: 0,
    discountPercent: 0,
    category: 'navidad',
    images: [`${IMG}/gjB1MsFh/rena-1.png`],
    customizable: false,
    featured: false,
    active: true,
    createdAt: '2026-03-12',
  },
  {
    id: 'nav-25',
    subcategory: 'renos',
    name: 'Rena con Accesorios',
    description: 'Rena navidena con gorro y bufanda. Cada accesorio es elaborado a mano con atencion al detalle.',
    price: 0,
    discountPercent: 0,
    category: 'navidad',
    images: [`${IMG}/C1738Yvp/rena2.png`],
    customizable: false,
    featured: false,
    active: true,
    createdAt: '2026-03-12',
  },
  {
    id: 'nav-26',
    subcategory: 'renos',
    name: 'Reno Clasico',
    description: 'Reno navideno clasico en foamy. Pieza tradicional con acabados artesanales de calidad.',
    price: 0,
    discountPercent: 0,
    category: 'navidad',
    images: [`${IMG}/7hbWTzG9/Reno-1.png`],
    customizable: false,
    featured: false,
    active: true,
    createdAt: '2026-03-13',
  },
  {
    id: 'nav-27',
    subcategory: 'renos',
    name: 'Reno Decorativo',
    description: 'Reno artesanal con detalles especiales. Perfecto para complementar tu decoracion navidena.',
    price: 0,
    discountPercent: 0,
    category: 'navidad',
    images: [`${IMG}/BQXrjrHV/Reno-3.png`],
    customizable: false,
    featured: false,
    active: true,
    createdAt: '2026-03-13',
  },
  {
    id: 'nav-28',
    subcategory: 'renos',
    name: 'Reno Grande',
    description: 'Reno navideno tamano grande. Pieza central ideal para la decoracion de tu hogar.',
    price: 0,
    discountPercent: 0,
    category: 'navidad',
    images: [`${IMG}/J4GfsfZp/Reno-4.png`],
    customizable: false,
    featured: false,
    active: true,
    createdAt: '2026-03-13',
  },
  {
    id: 'nav-29',
    subcategory: 'renos',
    name: 'Reno Elegante',
    description: 'Reno navideno con acabado elegante y sofisticado. Detalles pintados a mano.',
    price: 0,
    discountPercent: 0,
    category: 'navidad',
    images: [`${IMG}/nrwNd2b1/reno-5.png`],
    customizable: false,
    featured: false,
    active: true,
    createdAt: '2026-03-14',
  },
  {
    id: 'nav-30',
    subcategory: 'renos',
    name: 'Reno con Bufanda',
    description: 'Reno artesanal con bufanda tejida. Combina lo tierno con lo navideno.',
    price: 0,
    discountPercent: 0,
    category: 'navidad',
    images: [`${IMG}/VvN3BTTq/reno-7.png`],
    customizable: false,
    featured: false,
    active: true,
    createdAt: '2026-03-14',
  },
  {
    id: 'nav-31',
    subcategory: 'renos',
    name: 'Reno Sentado',
    description: 'Tierno reno en posicion sentada. Pieza artesanal compacta y decorativa.',
    price: 0,
    discountPercent: 15,
    category: 'navidad',
    images: [`${IMG}/GtpZJNNY/reno-7-1.png`],
    customizable: false,
    featured: false,
    active: true,
    createdAt: '2026-03-14',
  },
  {
    id: 'nav-32',
    subcategory: 'renos',
    name: 'Reno Azul',
    description: 'Reno navideno en tonos azules. Diseno moderno para una Navidad con estilo.',
    price: 0,
    discountPercent: 0,
    category: 'navidad',
    images: [`${IMG}/SRtHZdFZ/reno-azul.png`],
    customizable: false,
    featured: false,
    active: true,
    createdAt: '2026-03-15',
  },
  {
    id: 'nav-33',
    subcategory: 'renos',
    name: 'Reno Cafe',
    description: 'Reno artesanal en tonos tierra y cafe. Estilo rustico con encanto navideno.',
    price: 0,
    discountPercent: 0,
    category: 'navidad',
    images: [`${IMG}/V6fTmpzH/reno-cafe.png`],
    customizable: false,
    featured: false,
    active: true,
    createdAt: '2026-03-15',
  },
  {
    id: 'nav-34',
    subcategory: 'renos',
    name: 'Reno Muneco',
    description: 'Adorable reno estilo muneco. Pieza artesanal suave y con detalles encantadores.',
    price: 0,
    discountPercent: 0,
    category: 'navidad',
    images: [`${IMG}/J0t2BXDM/reno-muneco.png`],
    customizable: false,
    featured: false,
    active: true,
    createdAt: '2026-03-15',
  },
  {
    id: 'nav-36',
    subcategory: 'renos',
    name: 'Pareja de Renos Elegantes',
    description: 'Pareja de renos con acabado elegante. Set decorativo premium para la temporada.',
    price: 0,
    discountPercent: 0,
    category: 'navidad',
    images: [`${IMG}/4y3rbMMx/reno-pareja-2.png`],
    customizable: false,
    featured: false,
    active: true,
    createdAt: '2026-03-16',
  },
  {
    id: 'nav-37',
    subcategory: 'renos',
    name: 'Reno Patas Largas',
    description: 'Reno artesanal con patas largas colgantes. Ideal para repisas, mesas o bordes de muebles.',
    price: 0,
    discountPercent: 0,
    category: 'navidad',
    images: [`${IMG}/0QnTSxVH/reno-patas.png`],
    customizable: false,
    featured: false,
    active: true,
    createdAt: '2026-03-16',
  },
  {
    id: 'nav-38',
    subcategory: 'renos',
    name: 'Reno Premium',
    description: 'Reno navideno edicion premium. Pieza artesanal con los mejores acabados y detalles.',
    price: 0,
    discountPercent: 0,
    category: 'navidad',
    images: [`${IMG}/B6prFsmr/reno11.png`],
    customizable: false,
    featured: false,
    active: true,
    createdAt: '2026-03-17',
  },
  {
    id: 'nav-40',
    subcategory: 'renos',
    name: 'Reno Tierno',
    description: 'Reno artesanal con expresion tierna y amorosa. Perfecto como regalo navideno.',
    price: 0,
    discountPercent: 0,
    category: 'navidad',
    images: [`${IMG}/3NbzL15W/reno-8.png`],
    customizable: false,
    featured: false,
    active: true,
    createdAt: '2026-03-17',
  },
  {
    id: 'nav-41',
    subcategory: 'renos',
    name: 'Reno Navideno Especial',
    description: 'Reno con diseno especial y detalles unicos. Pieza de coleccion hecha a mano.',
    price: 0,
    discountPercent: 0,
    category: 'navidad',
    images: [`${IMG}/cCJVMjjf/reno-8-1.png`],
    customizable: false,
    featured: false,
    active: true,
    createdAt: '2026-03-17',
  },
  {
    id: 'nav-42',
    subcategory: 'renos',
    name: 'Reno con Gorro',
    description: 'Reno navideno con gorro de Papa Noel. Combinacion perfecta de ternura y Navidad.',
    price: 0,
    discountPercent: 0,
    category: 'navidad',
    images: [`${IMG}/2y5PFJJL/reno-9.png`],
    customizable: false,
    featured: false,
    active: true,
    createdAt: '2026-03-18',
  },
  {
    id: 'nav-43',
    subcategory: 'pie_arbol_cojines',
    name: 'Forro Cojin Navideno',
    description: 'Forro de cojin decorativo con motivos navidenos. Complemento perfecto para tu sala.',
    price: 0,
    discountPercent: 0,
    category: 'navidad',
    images: [`${IMG}/4yMFv3VQ/forro-cojin.png`],
    customizable: true,
    featured: false,
    active: true,
    createdAt: '2026-03-18',
  },

  // ========== HALLOWEEN ==========
  {
    id: 'hal-01',
    name: 'Bruja Artesanal',
    description: 'Encantadora bruja hecha a mano en foamy. Con su sombrero puntiagudo y escoba, es la pieza perfecta para decorar en Halloween.',
    price: 0,
    discountPercent: 30,
    category: 'halloween',
    images: [`${IMG}/rmjB4cf1/bruja-1.png`],
    customizable: true,
    featured: true,
    active: true,
    createdAt: '2026-03-01',
  },
  {
    id: 'hal-02',
    name: 'Cojines de Brujas',
    description: 'Set de cojines decorativos con tematica de brujas. Elaborados a mano con telas de alta calidad y disenos originales.',
    price: 0,
    discountPercent: 25,
    category: 'halloween',
    images: [`${IMG}/k47rDDvh/cojines-brujas.png`],
    customizable: true,
    featured: true,
    active: true,
    createdAt: '2026-03-02',
  },
  {
    id: 'hal-03',
    name: 'Espantapajaros de Halloween',
    description: 'Divertido espantapajaros artesanal para la temporada de Halloween. Pieza unica con detalles coloridos y expresion amigable.',
    price: 0,
    discountPercent: 0,
    category: 'halloween',
    images: [`${IMG}/gj5By08v/espanta-pajaros.jpg`],
    customizable: false,
    featured: true,
    active: true,
    createdAt: '2026-03-03',
  },
  {
    id: 'hal-04',
    name: 'Gato con Botas Halloween',
    description: 'Adorable gato con botas en version Halloween. Figura artesanal en foamy con sombrero de bruja y accesorios tematicos.',
    price: 0,
    discountPercent: 0,
    category: 'halloween',
    images: [`${IMG}/W38BZj57/Gato-con-botas.png`],
    customizable: false,
    featured: false,
    active: true,
    createdAt: '2026-03-04',
  },
  {
    id: 'hal-05',
    name: 'Gato con Botas Especial',
    description: 'Version especial del gato con botas para Halloween. Con detalles extra y acabado premium hecho a mano.',
    price: 0,
    discountPercent: 0,
    category: 'halloween',
    images: [`${IMG}/Qtm27sfJ/Gato-con-botas-2.png`],
    customizable: false,
    featured: false,
    active: true,
    createdAt: '2026-03-04',
  },

  // ========== DESAYUNOS SORPRESA ==========
  {
    id: 'des-01',
    subcategory: 'pie_arbol_cojines',
    name: 'Familia Artesanal en Foamy',
    description: 'Hermosa familia de figuras artesanales en foamy. Ideal para decorar en Navidad o como regalo especial.',
    price: 0,
    discountPercent: 20,
    category: 'navidad',
    images: [`${IMG}/Y2ncqrG4/familia-1.png`],
    customizable: true,
    featured: true,
    active: true,
    createdAt: '2026-03-01',
  },
  {
    id: 'des-02',
    name: 'Decoracion en Foamy #1',
    description: 'Pieza decorativa artesanal en foamy para sorprender en desayunos especiales. Hecha a mano con amor y dedicacion.',
    price: 0,
    discountPercent: 0,
    category: 'desayunos_sorpresa',
    images: [`${IMG}/gj0fq55p/fommy-1.png`],
    customizable: true,
    featured: false,
    active: true,
    createdAt: '2026-03-02',
  },
  {
    id: 'des-03',
    name: 'Decoracion en Foamy #2',
    description: 'Figura decorativa artesanal perfecta para ambientar desayunos sorpresa y celebraciones especiales.',
    price: 0,
    discountPercent: 0,
    category: 'desayunos_sorpresa',
    images: [`${IMG}/wMBScPPp/fommy-2.png`],
    customizable: true,
    featured: false,
    active: true,
    createdAt: '2026-03-03',
  },
  {
    id: 'des-04',
    name: 'Decoracion en Foamy #3',
    description: 'Detalle artesanal en foamy con diseno original. Complemento ideal para hacer memorable cualquier sorpresa.',
    price: 0,
    discountPercent: 15,
    category: 'desayunos_sorpresa',
    images: [`${IMG}/SRKw75PB/fommy-3.png`],
    customizable: true,
    featured: true,
    active: true,
    createdAt: '2026-03-04',
  },
  {
    id: 'des-05',
    name: 'Decoracion en Foamy #4',
    description: 'Pieza artesanal colorida y creativa. Cada detalle es pensado para alegrar el dia de alguien especial.',
    price: 0,
    discountPercent: 0,
    category: 'desayunos_sorpresa',
    images: [`${IMG}/Kzf6TF9c/fommy-4.png`],
    customizable: true,
    featured: false,
    active: true,
    createdAt: '2026-03-05',
  },
  {
    id: 'des-06',
    name: 'Decoracion en Foamy #5',
    description: 'Detalle artesanal unico elaborado en foamy de alta calidad. Perfecto para complementar desayunos y regalos.',
    price: 0,
    discountPercent: 0,
    category: 'desayunos_sorpresa',
    images: [`${IMG}/26GsWmHz/fommy-5.png`],
    customizable: true,
    featured: false,
    active: true,
    createdAt: '2026-03-06',
  },
  {
    id: 'des-07',
    name: 'Decoracion en Foamy #6',
    description: 'Figura decorativa hecha a mano con materiales premium. Cada pieza es unica e irrepetible.',
    price: 0,
    discountPercent: 0,
    category: 'desayunos_sorpresa',
    images: [`${IMG}/cHhp3ZDd/fommy-6.png`],
    customizable: true,
    featured: false,
    active: true,
    createdAt: '2026-03-07',
  },
  {
    id: 'des-08',
    name: 'Tejido Artesanal #1',
    description: 'Pieza tejida a mano con lana de alta calidad. Detalle unico para acompanar desayunos y celebraciones.',
    price: 0,
    discountPercent: 0,
    category: 'tejidos',
    images: [`${IMG}/tRS0CqZJ/tejido-1.png`],
    customizable: true,
    featured: false,
    active: true,
    createdAt: '2026-03-08',
  },
  {
    id: 'des-09',
    name: 'Tejido Artesanal #2',
    description: 'Creacion tejida a mano con patrones originales. Cada pieza lleva horas de trabajo artesanal.',
    price: 0,
    discountPercent: 0,
    category: 'tejidos',
    images: [`${IMG}/Pf3GrXp5/tejido-2-(1).png`],
    customizable: true,
    featured: false,
    active: true,
    createdAt: '2026-03-09',
  },
  {
    id: 'des-10',
    name: 'Tejido Artesanal #3',
    description: 'Pieza tejida con tecnica artesanal y colores vibrantes. Perfecta como detalle de regalo.',
    price: 0,
    discountPercent: 35,
    category: 'tejidos',
    images: [`${IMG}/7PsvYHG6/tejido-3.png`],
    customizable: true,
    featured: true,
    active: true,
    createdAt: '2026-03-10',
  },
  {
    id: 'des-11',
    name: 'Tejido Artesanal #4',
    description: 'Creacion artesanal tejida con dedicacion y cuidado en cada puntada. Pieza unica y especial.',
    price: 0,
    discountPercent: 0,
    category: 'tejidos',
    images: [`${IMG}/brF46gc4/tejido-4.png`],
    customizable: true,
    featured: false,
    active: true,
    createdAt: '2026-03-11',
  },
  {
    id: 'des-12',
    name: 'Tejido Artesanal #5',
    description: 'Tejido hecho a mano con materiales seleccionados. Ideal como detalle para ocasiones especiales.',
    price: 0,
    discountPercent: 0,
    category: 'tejidos',
    images: [`${IMG}/0jHhtnRY/tejido-6.png`],
    customizable: true,
    featured: false,
    active: true,
    createdAt: '2026-03-12',
  },
  {
    id: 'des-13',
    name: 'Tejido Artesanal Premium',
    description: 'Pieza tejida premium con acabados de alta calidad. El detalle perfecto para sorprender.',
    price: 0,
    discountPercent: 0,
    category: 'tejidos',
    images: [`${IMG}/Wzfx98LD/tejido-8.png`],
    customizable: true,
    featured: false,
    active: true,
    createdAt: '2026-03-13',
  },

  // ========== LAPICES Y CUADERNOS ==========
  {
    id: 'lap-01',
    name: 'Coleccion Completa de Lapices Decorados',
    description: 'Set completo de lapices decorados a mano con figuras en foamy. Cada lapiz tiene un personaje unico y colorido.',
    price: 0,
    discountPercent: 40,
    category: 'lapices_cuadernos',
    images: [`${IMG}/j29k6jP6/coleccion-lapiz.jpg`],
    customizable: false,
    featured: true,
    active: true,
    createdAt: '2026-03-01',
  },
  {
    id: 'lap-02',
    name: 'Cuaderno Decorado #1',
    description: 'Cuaderno con portada decorada artesanalmente en foamy. Cada diseno es unico y hecho a mano.',
    price: 0,
    discountPercent: 0,
    category: 'lapices_cuadernos',
    images: [`${IMG}/B6JWttBX/cuaderno-1.png`],
    customizable: true,
    featured: true,
    active: true,
    createdAt: '2026-03-02',
  },
  {
    id: 'lap-03',
    name: 'Cuaderno Decorado #2',
    description: 'Cuaderno personalizado con decoracion artesanal. Ideal para regalar o para uso escolar.',
    price: 0,
    discountPercent: 0,
    category: 'lapices_cuadernos',
    images: [`${IMG}/fLM4kkfT/cuaderno-2.png`],
    customizable: true,
    featured: false,
    active: true,
    createdAt: '2026-03-03',
  },
  {
    id: 'lap-04',
    name: 'Cuaderno Decorado #3',
    description: 'Portada decorada con figuras de foamy hechas a mano. Cada cuaderno es una obra de arte.',
    price: 0,
    discountPercent: 20,
    category: 'lapices_cuadernos',
    images: [`${IMG}/fbcnwYmT/cuaderno-3.png`],
    customizable: true,
    featured: false,
    active: true,
    createdAt: '2026-03-04',
  },
  {
    id: 'lap-05',
    name: 'Cuaderno Decorado #4',
    description: 'Cuaderno con portada artesanal en foamy. Diseno creativo y colorido para destacar en clase.',
    price: 0,
    discountPercent: 0,
    category: 'lapices_cuadernos',
    images: [`${IMG}/MG72W1VZ/cuaderno-4.png`],
    customizable: true,
    featured: false,
    active: true,
    createdAt: '2026-03-05',
  },
  {
    id: 'lap-06',
    name: 'Cuaderno Decorado #5',
    description: 'Cuaderno con decoracion artesanal unica. Perfecto como regalo o para uso personal.',
    price: 0,
    discountPercent: 0,
    category: 'lapices_cuadernos',
    images: [`${IMG}/3wX5K2m8/cuaderno-5.png`],
    customizable: true,
    featured: false,
    active: true,
    createdAt: '2026-03-06',
  },
  {
    id: 'lap-07',
    name: 'Cuaderno Decorado #6',
    description: 'Cuaderno premium con portada elaborada en foamy. Acabados finos y materiales de calidad.',
    price: 0,
    discountPercent: 0,
    category: 'lapices_cuadernos',
    images: [`${IMG}/0NYR87Dy/cuaderno-6.png`],
    customizable: true,
    featured: false,
    active: true,
    createdAt: '2026-03-07',
  },
  {
    id: 'lap-08',
    name: 'Lapiz Decorado Figura #1',
    description: 'Lapiz con figura decorativa en foamy hecha a mano. Cada pieza tiene un personaje adorable.',
    price: 0,
    discountPercent: 0,
    category: 'lapices_cuadernos',
    images: [`${IMG}/KzmX44Dp/lapiz-1.png`],
    customizable: false,
    featured: false,
    active: true,
    createdAt: '2026-03-08',
  },
  {
    id: 'lap-09',
    name: 'Lapiz Decorado Figura #2',
    description: 'Lapiz artesanal con decoracion en foamy. Personaje colorido y divertido para el colegio.',
    price: 0,
    discountPercent: 0,
    category: 'lapices_cuadernos',
    images: [`${IMG}/qRpfggxm/lapiz-2.png`],
    customizable: false,
    featured: false,
    active: true,
    createdAt: '2026-03-09',
  },
  {
    id: 'lap-10',
    name: 'Lapiz Decorado Figura #3',
    description: 'Lapiz con puntero artesanal en foamy. Diseno unico hecho a mano con mucho detalle.',
    price: 0,
    discountPercent: 0,
    category: 'lapices_cuadernos',
    images: [`${IMG}/26Cp3372/lapiz-3.png`],
    customizable: false,
    featured: false,
    active: true,
    createdAt: '2026-03-10',
  },
  {
    id: 'lap-11',
    name: 'Lapiz Decorado Figura #4',
    description: 'Lapiz con personaje decorativo. Ideal como detalle para fiestas infantiles o regalos.',
    price: 0,
    discountPercent: 0,
    category: 'lapices_cuadernos',
    images: [`${IMG}/d1JMDDjn/lapiz-4.png`],
    customizable: false,
    featured: false,
    active: true,
    createdAt: '2026-03-11',
  },
  {
    id: 'lap-12',
    name: 'Lapiz Decorado Figura #5',
    description: 'Lapiz artesanal con figura en foamy. Accesorio escolar divertido y original.',
    price: 0,
    discountPercent: 0,
    category: 'lapices_cuadernos',
    images: [`${IMG}/qRpfggxc/lapiz-5.png`],
    customizable: false,
    featured: false,
    active: true,
    createdAt: '2026-03-12',
  },
  {
    id: 'lap-13',
    name: 'Lapiz Decorado Figura #6',
    description: 'Lapiz con decoracion artesanal unica. Cada pieza es diferente y especial.',
    price: 0,
    discountPercent: 0,
    category: 'lapices_cuadernos',
    images: [`${IMG}/hjKFhh1L/lapiz-6.png`],
    customizable: false,
    featured: false,
    active: true,
    createdAt: '2026-03-13',
  },
  {
    id: 'lap-14',
    name: 'Lapiz Decorado Figura #7',
    description: 'Lapiz con puntero en foamy hecho a mano. Diseno exclusivo para los mas creativos.',
    price: 0,
    discountPercent: 0,
    category: 'lapices_cuadernos',
    images: [`${IMG}/nzn8MMG7/lapiz-7.png`],
    customizable: false,
    featured: false,
    active: true,
    createdAt: '2026-03-14',
  },
  {
    id: 'lap-15',
    name: 'Lapiz Decorado Figura #8',
    description: 'Lapiz artesanal con figura colorida. El accesorio perfecto para hacer divertido el estudio.',
    price: 0,
    discountPercent: 0,
    category: 'lapices_cuadernos',
    images: [`${IMG}/W3sRttwZ/lapiz-8.png`],
    customizable: false,
    featured: false,
    active: true,
    createdAt: '2026-03-15',
  },
  {
    id: 'lap-16',
    name: 'Lapiz Decorado Figura #9',
    description: 'Lapiz con figura artesanal en foamy. Detalle especial para amantes de los utiles creativos.',
    price: 0,
    discountPercent: 0,
    category: 'lapices_cuadernos',
    images: [`${IMG}/nzn8MMG9/lapiz-9.png`],
    customizable: false,
    featured: false,
    active: true,
    createdAt: '2026-03-16',
  },
];

export const formatPrice = (price: number): string => {
  if (price === 0) return 'Consultar precio';
  return new Intl.NumberFormat('es-CO', {
    style: 'currency',
    currency: 'COP',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(price);
};

export const getDiscountedPrice = (price: number, discountPercent: number): number => {
  if (price === 0) return 0;
  return Math.round(price * (1 - discountPercent / 100));
};
